rticommunity/rticonnextdds-cmake-utils

- cmake/Modules/FindRTIConnextDDS.cmake
An incompatibility with CMake 3.12 was added previously. Mitigate that incompatibility.
> Move back to set function

- cmake/Modules/FindRTIConnextDDS.cmake
> cpp2_api now depends on c_api rather than cpp_api

- cmake/Modules/FindRTIConnextDDS.cmake
> Add WolfSSL integration

- cmake/Modules/ConnextDdsAddExample.cmake
Closes #27
Added script with history from the examples repository.
> Adds add-example cmake module

- cmake/Modules/FindRTIConnextDDS.cmake
> Re-adds ARMv8 Linux support

- cmake/Modules/FindRTIConnextDDS.cmake
> Sanitize Codegen version output

- cmake/Modules/FindRTIConnextDDS.cmake
> Re-adds QNX x64 and ARMv8 support

- cmake/Modules/FindRTIConnextDDS.cmake
> Use a single call to find OpenSSL

- cmake/Modules/FindRTIConnextDDS.cmake
> Fixes architecture getting from the environment

- Jenkinsfile
- resources/docker/Dockerfile.x64Linux
Resolves #40 
This PR adds continuous integration to the repository making use of [rticommunity/rticonnextdds-examples](https://github.com/rticommunity/rticonnextdds-examples) repository.
> Feature/40 CI for the repository

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/find-package.md
- .github/PULL_REQUEST_TEMPLATE/general.md
- Jenkinsfile
> Implement first version of issue and pull-request templates

- cmake/Modules/FindRTIConnextDDS.cmake
Fixes #51 
Documentation expansion and fixes.
> [FindPackage] Feature/51: Fix documentation issues

- cmake/Modules/ConnextDdsAddExample.cmake
- cmake/Modules/FindRTIConnextDDS.cmake
Fix #62
Fix #57
Fix #60
Fix #59
Fix #58
- Propagates dependencies variable in the ConnextDdsAddExample script
- Adds RTI_STATIC definition
- Adds WolfSSL as a dependency of security plugins
- Single wolfssl find_package call
- Secure security plugins dir seasrch paths variables
> Fix various security_plugins issues

- cmake/Modules/FindRTIConnextDDS.cmake
> INSTALL-719: renamed edisc imported target

- cmake/Modules/UseOpenSSL.cmake
Fixes #67 
Update UseOpenSSL.cmake and remove unused code.
> Update UseOpenSSL.cmake Fixes #67

- cmake/Modules/FindRTIConnextDDS.cmake
> Fix #88: Explain possible erros when forcing the library build type

- cmake/Modules/FindRTIConnextDDS.cmake
* Fix #88: Explain possible errors when forcing the library build type
Ref INSTALL-797
Fixes #<issue id>
> Cherry-pick 02d3017: Fix #88

- README.md
>  Add 7.1.0 release branch link in README.md

- cmake/Modules/FindRTIConnextDDS.cmake
Fixes #97, fixes #95
Remove the old library
> GH-97: Remove old library

- cmake/Modules/FindRTIConnextDDS.cmake
> GH-99: Add support for QOS architecture to the FindPackage

- README.md
> Add release 7.2.0 link to the README

- cmake/Modules/FindRTIConnextDDS.cmake
Add support for arm64win64
| Mode            | Result | Comments |
| --------------- | ------ | -------- |
| dynamic/release | OK     | --       |
| dynamic/debug   | OK     | --       |
| static/release  | OK     | --       |
| static/debug    | OK     | --       |
> INSTALL-988 Add support for arm64Win64VS2022

- Jenkinsfile
- ci.yaml
- resources/ci/buildSingleMode.groovy
- resources/ci/config.yaml
- resources/ci/docker/Dockerfile.x64Linux3gcc4.8.2
- resources/ci/docker/Dockerfile.x64Linux4gcc7.3.0
- resources/ci/patches/6.1.2Patch.groovy
- resources/ci/patches/submodulePatch.groovy
Examples branch: PR-683
The new pipeline will be in charge of running a dynamic series of jobs. These jobs will consist in:
- all the LTS versions of Connext (release branches)
- the master branch of the examples (latest released version)
- the develop branch (development version)
- the associated examples PR (if existent)
All these jobs will be executed in all the supported architectures of the FindPackage (for starters the Linux architecture is added).
> INSTALL-944: Refactor CI pipeline to launch rticonnextdds-examples jobs

- Jenkinsfile
Remove when conditional to run CI with every change.
> INSTALL-944: Remove when conditional

- Jenkinsfile
- resources/ci/buildArchitectureConfigurations.groovy
- resources/ci/buildConfiguration.groovy
- resources/ci/config.yaml
Create a warning quality gate.
> INSTALL-1063: Stabilize 6.1.2 branch

- cmake/Modules/FindRTIConnextDDS.cmake
Fixes #124
Remove unrequired dependency
> INSTALL-1084 #124 Remove unrequired dependency on Recording Service
